### ISSUE TITLE
The right way to close term buff

### ISSUE THREAD

**Issue by SheffeyG** [siduck76/NvChad#2844] opened 2024-05-18 19:49 UTC
**Describe the bug**
I mapped keys to close terminal and term runner:
```
-- Close terminal
local function close_terminal()
    local win = vim.api.nvim_get_current_win()
    vim.api.nvim_win_close(win, true)
end

map("t", "<ESC>", close_terminal, { desc = "Close Terminal" })

-- Code Runner
local function code_runner()
    vim.cmd("write");
    require("nvchad.term").runner({
        -- id = "htoggleTerm",
        pos = "sp",

        cmd = function()
            local file = vim.fn.expand("%")

            local ft_cmds = {
                python = "python3 " .. file,
                cpp = "clear && g++ -o out " .. file .. " && ./out",
                c = "clear && gcc -o out " .. file .. " && ./out",
            }

            return ft_cmds[vim.bo.ft]
        end,
    })
end

map({ "n" }, "<leader>cr", code_runner)
```
everytime I close the runner terminal with `ESC` key, and re-run the term runner, the error shows:
```
E5108: Error executing lua: ...effey/.local/share/nvim/lazy/ui/lua/nvchad/term/init.lua:142: attempt to concatenate local 'cmd' (a nil value)
stack traceback:
        ...effey/.local/share/nvim/lazy/ui/lua/nvchad/term/init.lua:142: in function 'runner'
        /home/sheffey/.config/nvim/lua/mappings.lua:35: in function </home/sheffey/.config/nvim/lua/mappings.lua:33>
```
**To Reproduce**
1. `<leader>cr` to run term runner
2. `<ESC>` to close the terminal
3. `<leader>cr` to run term runner again

**Expected behavior**
nothing should be happen.

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/57262511/d6b9389e-ad0e-4dd1-b34f-c5e2f93345da)

**Desktop (please complete the following information):**
 - Operating System: Win10 WSL
 - Terminal: terminal zsh
 - Neovim 0.10

**Additional context**
I am not sure what's the correct way to close the term runner terminal, I tried <M-h> to toggle it, it can't. Alse I tried set the id to `htoggleTerm` to make it togglable, but same error shows.

**Comment by liangmiQwQ** [comment] 2024-05-18 23:22
I want to know how I can close the term, too.

**Comment by siduck** [comment] 2024-05-18 23:31
press leader x to close its window or `bd!` command to remove it completely

**Comment by siduck** [comment] 2024-05-18 23:31
and id is needed

**Closed as completed by siduck** 2024-05-18 23:31 UTC

**Comment by SheffeyG** [comment] 2024-05-19 05:12
@siduck I tried `leader-x` to close the terminal:
1. `leader-cr` to open runner terminal
2. `C-x` to leave terminal mode
3. `leader-x` to close the buffer
4. `leader-cr` to run the code again
and then the error again:
```
E5108: Error executing lua: .../home/.local/share/nvim/lazy/ui/lua/nvchad/term/init.lua:142: attempt to concat
enate local 'cmd' (a nil value)
stack traceback:
        .../home/.local/share/nvim/lazy/ui/lua/nvchad/term/init.lua:142: in function 'runner'
        ...data/com.termux/files/home/.config/nvim/lua/mappings.lua:37: in function <...data/com.termux/files/
home/.config/nvim/lua/mappings.lua:35>
```
it seems that the runner can't get the buffer id, tho I set the runner id.        `id = "runner"`

**Comment by SheffeyG** [comment] 2024-05-19 05:17
And if I press `C-d` to leave the terminal, then re-run the runner is fine

**Comment by siduck** [comment] 2024-05-19 06:01
works fine here @SheffeyG , i hope you latest version of UI plugin, did lazy sync?

https://github.com/NvChad/NvChad/assets/59060246/12f7e2ff-8018-45f8-9930-56e17e991abf

**Comment by SheffeyG** [comment] 2024-05-19 08:09
@siduck Yes, and the error only happened after I updated to the latest ui plugin yesterday, so I revert the ui plugin to commit `4f50777` everything is okay now.

**Comment by siduck** [comment] 2024-05-19 08:26
> 4f50777

thats weird, as you can clearly see in the video i cant reproduce it! can you show a video?

**Comment by SheffeyG** [comment] 2024-05-19 08:37
@siduck As I comment at [here](https://github.com/NvChad/ui/pull/282) and the error msg:
```
E5108: Error executing lua: .../home/.local/share/nvim/lazy/ui/lua/nvchad/term/init.lua:142: attempt to concat
enate local 'cmd' (a nil value)
```

**Comment by siduck** [comment] 2024-05-19 08:44
@SheffeyG  fixed
