### ISSUE TITLE
Telescope syntax highlighting is not working until I open a file

### ISSUE THREAD

**Issue by Shunseii** [siduck76/NvChad#2084] opened 2023-06-04 06:51 UTC
**Describe the bug**
The syntax highlighting in the Telescope window is not respecting my configuration and uses the default, high-contrast colours when I first open it after opening a project. However, if I open a file and then open Telescope again, the syntax highlighting is back to normal. It's happening with all the languages that I've checked.

**To Reproduce**
1. Navigate to a project directory
2. Open the directory in neovim by running `nvim`
3. Open Telescope with, say `<leader>ff`
4. See the default syntax highlighting 

**Expected behavior**
The syntax highlighting should be consistent and correct in the Telescope window.

**Screenshots**
When I initially open Telescope before opening any project files (shows the broken syntax highlighting)
![image](https://github.com/NvChad/NvChad/assets/20803729/dc67d1a5-ac91-44b7-9e9b-0ae0b05e3b0d)

After I open some file in the project then open Telescope again (shows the expected highlighting):
![image](https://github.com/NvChad/NvChad/assets/20803729/840444ba-8e68-4667-b005-cd94e0686161)

**Desktop (please complete the following information):**
 - Operating System: Pop!_OS 22.04
 - Terminal: Gnome Terminal
 - Neovim Version: V0.9.0

**Additional context**
I have the exact same setup on my laptop (issue occurs on my desktop) in terms of OS and NvChad configuration and I don't see it on my laptop. In fact, I wasn't even seeing this on my desktop until I installed the following LSPs with Mason by adding the following lines to `ensure_installed` and then `:MasonInstallAll` (since I realized I didn't have them installed nor explicitly required in my config):
- "elixir-ls",
- "eslint-lsp",
- "julia-lsp",
- "rust-analyzer",
- "tailwindcss-language-server",
- "typescript-language-server",

I've also copied over the entire `custom/` directory from my laptop to my desktop (although they should've been identical from the start) to double-check, but I'm facing the same issue.

I suspect I just missed a step somewhere when I was setting it up again on my desktop (which I did after my laptop) rather than this being a bug, but I'm really at a loss as to how I can debug this :(

**Comment by siduck** [comment] 2023-06-04 08:37
unable to reproduce! 

make sure you have these tsparsers installed :

html css javascript  typescript tsx

**Comment by Shunseii** [comment] 2023-06-04 12:05
I verified just now with `:TSInstallInfo` that I have them all installed. The syntax highlighting works in almost all cases, it's just when I open the Telescope window before I open any file -- it's as if something doesn't load until I open a file? Really strange

**Comment by Shunseii** [comment] 2023-06-04 12:30
So I backed up my custom dir and reinstalled NvChad with the example custom configuration and I still see the issue :/ And it's the same situation as before: only Telescope has the broken highlighting, but everything else works. And if I open another file then open Telescope, it works fine

Before opening any other file:
![image](https://github.com/NvChad/NvChad/assets/20803729/1796dd9e-c64b-4fb5-87c4-a0d5a40acf86)

After I open a file:
![image](https://github.com/NvChad/NvChad/assets/20803729/4a91f525-a91e-414b-9839-dd775890ca13)

**Comment by siduck** [comment] 2023-06-04 14:06
thats really strange man, i cant reproduce it at all!

**Comment by vandenng** [comment] 2023-06-05 15:01
I can reproduce the above error on a blank buffer(only on startup); however, this is due to the nvim-treesitter plugin not being loaded until a file is opened. This is due to lazy loading configuration for nvim-treesitter. 

My suspicion is you are experiencing this aswell. To confirm, run `:TSInstall` before opening a telescope window to load the nvim-treesitter plugin and see if syntax highlighting populates properly.

**Comment by siduck** [comment] 2023-06-05 16:29
@vandenng nvimtree should still load on module regardlessly ! because telescope loads it

**Comment by Shunseii** [comment] 2023-06-05 17:35
@vandenng Ah interesting, yeah that does work!

**Comment by siduck** [comment] 2023-06-06 00:01
I'm unable to reproduce . Are you all using neovim v0.10?

https://github.com/NvChad/NvChad/assets/59060246/9dac390b-02c6-4fca-a559-51228c4cef68

**Comment by vandenng** [comment] 2023-06-06 11:47
Interesting... Here is some info regarding my setup:
nvim v0.9.1
NVchad v2.0 at commit f8a489ea1a670569eead0fe5651c0c48add743e8 
macOS v13.2.1

<img width="1660" alt="Screenshot 2023-06-06 at 7 45 25 AM" src="https://github.com/NvChad/NvChad/assets/35298900/00492607-496d-4119-88e9-2a38d715a705">


<img width="1869" alt="Screenshot 2023-06-06 at 7 46 28 AM" src="https://github.com/NvChad/NvChad/assets/35298900/872b8870-05ad-4b5e-a271-96fbed280b17">

**Comment by Shunseii** [comment] 2023-06-06 14:09
I'm on nvim v0.9 and running the latest version of NvChad 2.0 on Pop OS 22.04 LTS, although I do have the exact same setup on another machine where I can't reproduce the issue, so there might be something else that could be affecting it

**Comment by siduck** [comment] 2023-06-06 15:27
> I'm on nvim v0.9 and running the latest version of NvChad 2.0 on Pop OS 22.04 LTS, although I do have the exact same setup on another machine where I can't reproduce the issue, so there might be something else that could be affecting it

try vanilla nvchad

**Comment by Shunseii** [comment] 2023-06-07 02:24
Vanilla as in no custom configuration? I tried above after reinstalling and removing the custom configs, but still seeing it
![image](https://github.com/NvChad/NvChad/assets/20803729/1796dd9e-c64b-4fb5-87c4-a0d5a40acf86)

**Comment by siduck** [comment] 2023-06-07 02:38
> Vanilla as in no custom configuration? I tried above after reinstalling and removing the custom configs, but still seeing it ![image](https://user-images.githubusercontent.com/20803729/243177078-1796dd9e-c64b-4fb5-87c4-a0d5a40acf86.png)

please try to open a lua file...  or at least install the these tsparsers : html css javascript   typescript tsx

**Comment by azuwis** [comment] 2023-06-07 02:40
@Shunseii Try adding this to `~/.config/nvim/lua/custom/plugins.lua`:

```
return {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = "nvim-treesitter/nvim-treesitter",
  },
}
```

**Comment by siduck** [comment] 2023-06-07 02:59
i cant reproduce this issue at all... Please make sure you all have proper tsparsers installed.  lazy.nvim autoloads a plugin on whenever their module gets called. Telescope whenever opened will also show the file preview which underhood still runs some code to call treesitter probably so nvim-treesitter too :/

https://github.com/NvChad/NvChad/assets/59060246/54f7f8ca-ee91-4a90-84bb-d9d6bbbadce7

**Comment by azuwis** [comment] 2023-06-07 03:48
I have the some problem, adding "nvim-treesitter/nvim-treesitter" as dependencies of "nvim-telescope/telescope.nvim" fixes the problem.

If telescope need nvim-treesitter, maybe we should explicitly declare that? I can make a PR if you like to accept.

**Comment by siduck** [comment] 2023-06-07 05:37
> I have the some problem, adding "nvim-treesitter/nvim-treesitter" as dependencies of "nvim-telescope/telescope.nvim" fixes the problem.
> 
> If telescope need nvim-treesitter, maybe we should explicitly declare that? I can make a PR if you like to accept.

are you using latest version of neovim? like the v0.10 one

**Comment by azuwis** [comment] 2023-06-07 06:00
> are you using latest version of neovim? like the v0.10 one

neovim v0.9.1

**Comment by strix** [comment] 2023-06-07 18:02
It seems like this is a v0.9.x issue only. Not sure what changed in v0.10.x that prevents the issue from happening but I'm experiencing the same issue on 2 different machines (one running macOS, one running arch) both on v0.9.1

Either the fix above getting merged in or just having those affected manually add that change until we all get on a v0.10.x version.

**Comment by lucario387** [comment] 2023-06-08 01:07
I can reproduce this on nightly. This is just an after-effect of nvim-telescope/telescope.nvim#2499

**Comment by Shunseii** [comment] 2023-06-08 13:44
> @Shunseii Try adding this to `~/.config/nvim/lua/custom/plugins.lua`:
> 
> ```
> return {
>   {
>     "nvim-telescope/telescope.nvim",
>     dependencies = "nvim-treesitter/nvim-treesitter",
>   },
> }
> ```

@azuwis Ah yeah this fixes the issue on my end too, thanks! 🙏🏼

**Comment by Shunseii** [comment] 2023-06-08 13:48
@siduck Given that there's a nice workaround, I'm happy to close the issue -- should we keep open to discuss repro steps or fine to close?

**Comment by siduck** [comment] 2023-06-08 14:50
> @siduck Given that there's a nice workaround, I'm happy to close the issue -- should we keep open to discuss repro steps or fine to close?

i wont close this yet,  provide steps to reproduce , make a video with clean nvchad installation. If im able to reproduce it too then i'll add your change or you can make a PR :)

**Comment by Shunseii** [comment] 2023-06-08 19:54
Sounds good :) I'll try to get to this today or tomorrow!

**Comment by Shunseii** [comment] 2023-06-09 22:06
[repro.webm](https://github.com/NvChad/NvChad/assets/20803729/cb0a78c4-418e-48b5-8c53-5b06b7d91dec)

Steps:
- Backup custom dir and reinstall NvChad
- Open a directory with `nvim`
- Open Telescope window and notice that syntax highlighting is missing (for lua files in the video)
- Open a file and then open Telescope window again -> notice the syntax highlighting is working now 

Let me know if I can add any additional info that could help out or if I missed something !

**Comment by siduck** [comment] 2023-06-10 03:24
thanks @Shunseii i can reproduce it too now. it didnt reproduce in my config because it had this plugin 

 
![image](https://github.com/NvChad/NvChad/assets/59060246/094c63e9-d148-4f76-b90d-bba2f7d21b41)

So whenever I open telescope, i'll be in insert mode right? at that moment this plugin gets loaded and this plugin is related to treesitter so it calls some treesitter modules which then loads treesitter plugin.

Btw this telescope issue we're facing didnt exist before, recently telescope started using vim.treesitter** stuff instead of calling the treesitter plugin directly i think so i guess I'll merge your pr!

done : https://github.com/NvChad/NvChad/commit/c2a0bb1684236e0bfbf43465ab1e22419debd98d

**Closed as completed** 2023-06-10 03:25 UTC
