### ISSUE TITLE
Theme Toggle Overrides both themes to the same one in chadrc.

### ISSUE THREAD

**Issue by guzman109** [siduck76/NvChad#2732] opened 2024-03-14 17:19 UTC
**Describe the bug**
I updated to v2.5. Transfered all my configs to the new style. My `chadrc.lua` file looks like this for the themes

`
local M = {}
M.ui = {
	theme = "material-lighter",
	theme_toggle = {
		"material-darker",
		"material-lighter",
	},
}
return M
`
 Now when I toggle my theme using the clickable button, in my `chadrc.lua` file, theme_toggle changes to this,
`
M.ui = {
	theme = "material-lighter",
	theme_toggle = {
		"material-lighter",
		"material-lighter",
	},
}
`
**To Reproduce**
1. Set current theme and theme_toggle in chadrc.lua 
2. close nvim and terminal emulator
3. Open terminal and open nvim
4. Click the theme toggle button
5. Open chadrc.lua file and ti has been edited by the button

**Expected behavior**
Switch themes by clicking the button

**Desktop (please complete the following information):**
 - Kubuntu 23.10
 - Kitty 0.32.0
 - Neovim 0.95.0

**Additional context**
It worked before v2.5

**Comment by siduck** [comment] 2024-03-15 00:36
duplicate of https://github.com/NvChad/base46/issues/294

**Closed as completed by siduck** 2024-03-15 00:36 UTC
