### ISSUE TITLE
Improper rendering of Cheatsheet when using glyphs

### ISSUE THREAD

**Issue by mastermach50** [siduck76/NvChad#1898] opened 2023-04-06 17:16 UTC
## Bug
The Cheatsheet is not rendered properly when glyphs from nerd font are used in the keymap description.

## Expected Behavior
The Cheetsheet is rendered properly

## Steps to reproduce
1. Add glyphs to keymap description
1. Open Neovim
1. Open Cheatsheet

## Screenshots
![image](https://user-images.githubusercontent.com/64970593/230449172-6014ac89-4bd2-47c1-ab5d-216a7896fcc2.png)

## System
- OS: Windows 10 Pro 22H2
- Terminal: Windows Terminal

## My Config
https://github.com/MasterMach50/NvChad-config

**Comment by siduck** [comment] 2023-04-06 17:37
duplicate of https://github.com/NvChad/ui/issues/74

**Closed as completed by siduck** 2023-04-06 17:37 UTC
