### ISSUE TITLE
Integrated terminal in NVChad doesn't recognize commands (using fish-shell)

### ISSUE THREAD

**Issue by BAD-WOLF** [siduck76/NvChad#3064] opened 2024-10-22 21:48 UTC
Thanks for the response! However, the issue seems to be related to NVChad itself, not just the terminal. To clarify, I have the following configuration in my `init.lua` file:

```lua
{
    "mtoohey31/cmp-fish", 
    ft = "fish",  -- Load the plugin only for .fish files
    dependencies = { "hrsh7th/nvim-cmp" },  -- Ensure cmp is available
    config = function()
        local cmp = require('cmp')
        cmp.setup({
            sources = cmp.config.sources({
                { name = 'fish' }
            })
        })
    end
},
```

However, when trying to use the `cmp-fish` plugin, I am getting the following error:

```
Error detected while processing TextChangedI Autocommands for "*":
Error executing lua callback: Vim:E475: Invalid value for argument cmd: 'fish' is not executable
```

I also tried specifying the path to `fish` manually with the configuration below:

```lua
{ name = 'fish', option = { fish_path = "/usr/bin/fish" } }
```

But I still get the same error:

```
Error detected while processing TextChangedI Autocommands for "*":
Error executing lua callback: Vim:E475: Invalid value for argument cmd: '/usr/bin/fish' is not executable
```

What's strange is that the error also occurs directly in the terminal, as I showed in the video above. So it doesn't seem to be an issue with an additional plugin that I am trying to integrate, but rather with NVChad itself or how it is handling commands and the terminal.

**Additional steps to reproduce:**
1. Set up NVChad with the `cmp-fish` plugin.
2. Try using `fish` as the default shell in the integrated terminal.
3. Observe the error related to the command not being recognized.

Any further guidance would be greatly appreciated, as this issue affects the functionality of the terminal and the shell within NVChad.

_Originally posted by @BAD-WOLF in https://github.com/NvChad/ui/issues/380#issuecomment-2429718280_

**Comment by siduck** [comment] 2024-10-23 00:23
duplicate of https://github.com/NvChad/ui/issues/380

**Closed as completed by siduck** 2024-10-23 00:23 UTC
