### ISSUE TITLE
Error detected, TextChangedI Autocommands for "<buffer=5>"

### ISSUE THREAD

**Issue by Staz0r** [siduck76/NvChad#3015] opened 2024-10-04 06:47 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim

**Additional context**

**Comment by siduck** [comment] 2024-10-04 08:05
duplicate of https://github.com/NvChad/ui/issues/348

**Closed as completed by siduck** 2024-10-04 08:05 UTC
