### ISSUE TITLE
Telescope find files opens buffer in insert mode

### ISSUE THREAD

**Issue by yoplat** [siduck76/NvChad#1977] opened 2023-04-30 16:51 UTC
**Describe the bug**
When using telescope to open files (find files or old files) the file buffer gets opened in insert mode

**To Reproduce**
1.  Launch Neovim
2. Launch telescope find files or old files
3. Select a file and open it

**Expected behavior**
Open buffer/file in normal mode

**Desktop:**
 - Operating System MacOS
 - Terminal Alacritty
 - Version of Neovim 0.9

**Comment by siduck** [comment] 2023-04-30 16:53
duplicate of https://github.com/NvChad/NvChad/issues/1978

**Closed as completed by siduck** 2023-04-30 16:53 UTC
