### ISSUE TITLE
It takes a long time to load "clangd"

### ISSUE THREAD

**Issue by GreenSleeper** [siduck76/NvChad#2139] opened 2023-06-20 02:19 UTC
So, I have `clangd` installed and configured according to the documentation, and when I open a cpp file in a large project like android project, it take about 15 seconds before `clangd` shows up at the status line, during that time, my nvim is very non-responsive, i can hardly move the cursor.
I tried to turn off `lsp_semantic_tokens`, still the same.
I'm not sure whether it's a `NvChad` problem, but I tried `LazyVim` too, didn't have this problem.
With small project, it works just fine.

**Comment by siduck** [comment] 2023-06-20 11:37
@GreenSleeper could   you record a video?

**Comment by GreenSleeper** [comment] 2023-06-21 02:34
Sorry, I'm using vim at work and I can't upload videos.
In practice, it doesn't affect my work flow that much, so if there's any inconvenience, just close this.

**Comment by GreenSleeper** [comment] 2023-06-26 06:26
https://github.com/NvChad/NvChad/assets/95287687/b9355dd3-3d5d-4ad2-838f-4a5b9ae68841

OK, it bugs me now.
When I open a file in a large repo, it takes almost half a minute for me to be able to move my cursor.

**Comment by GreenSleeper** [comment] 2023-06-26 06:51
can you reopen this?

**Comment by siduck** [comment] 2023-06-26 12:19
> can you reopen this?

can you make a video with non nvchad config too?

**Comment by GreenSleeper** [comment] 2023-06-26 12:49
![lazyvim](https://github.com/NvChad/NvChad/assets/95287687/a4a6cfe3-cc51-41b7-b9ed-0d6e1f00f326)

This is `LazyVim`.

**Comment by GreenSleeper** [comment] 2023-06-26 12:57
> nvchad.mp4 
> OK, it bugs me now. When I open a file in a large repo, it takes almost half a minute for me to be able to move my cursor.

it takes a long time before the "git module" and "lsp module" show up on statusline, maybe too much workload there?

**Comment by siduck** [comment] 2023-06-26 15:23
> > nvchad.mp4
> > OK, it bugs me now. When I open a file in a large repo, it takes almost half a minute for me to be able to move my cursor.
> 
> it takes a long time before the "git module" and "lsp module" show up on statusline, maybe too much workload there?

ignore the statusline components, see if the completions are available immediately

**Comment by GreenSleeper** [comment] 2023-06-27 01:04
> ignore the statusline components, see if the completions are available immediately

no lsp completions, just text completions.

**Comment by siduck** [comment] 2023-06-27 01:31
> > ignore the statusline components, see if the completions are available immediately
> 
> no lsp completions, just text completions.

go to default plugins file and remove init function of lspconfig and add lazy=false there, does that solve?

**Comment by GreenSleeper** [comment] 2023-06-27 01:37
yes, it does!

**Comment by siduck** [comment] 2023-06-27 01:39
me rn 
 
 
![image](https://github.com/NvChad/NvChad/assets/59060246/07767e4c-ff1a-4653-9dcb-f66f4ee77e2e)

**Comment by siduck** [comment] 2023-06-27 01:39
Can you share any large c++ public codebase ( like a github repo ) so i could test it here?

**Comment by GreenSleeper** [comment] 2023-06-27 01:56
You can use [`frameworks/native`](https://android.googlesource.com/platform/frameworks/native/)

but I've noticed that it's slow not only because the repo is large but also because the file I opened is large itself.
So you can just copy [SurfaceFlinger.cpp](https://android.googlesource.com/platform/frameworks/native/+/refs/heads/master/services/surfaceflinger/SurfaceFlinger.cpp) to your machine and test on it.

I opened it on a ubuntu server, it took about 10s to load clangd.

**Comment by siduck** [comment] 2023-07-09 00:24
https://github.com/NvChad/NvChad/assets/59060246/a8e17dd9-7aa6-43ad-be28-35fe44388493

unable to reproduce. 

Can you make a video with/without lazy=false to the lspconfig?

**Comment by GreenSleeper** [comment] 2023-07-09 07:30
I can't reproduce too, I don't know if it's because of some updates (plugins updates or clangd updates) or not, it' working normally now, but I noticed that the lsp progress module weren't showing anymore.



---Original---
From: ***@***.***&gt;
Date: Sun, Jul 9, 2023 08:25 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NvChad/NvChad] It takes a long time to load "clangd" (Issue#2139)




 
https://github.com/NvChad/NvChad/assets/59060246/a8e17dd9-7aa6-43ad-be28-35fe44388493
 
unable to reproduce.
 
Can you make a video comparing nvchad/lunarvim about this?

**Comment by siduck** [comment] 2023-07-09 08:45
@GreenSleeper the lsp progress stuff is on the ui repo, i noticed that it works when i move my cursor or go in insert mode, weird. I'll look into it. Closing this issue tho! open it when you get it again

**Closed as completed by siduck** 2023-07-09 08:45 UTC
