### ISSUE TITLE
SSL error on nvchad.com

### ISSUE THREAD

**Issue by oec** [siduck76/NvChad#1943] opened 2023-04-20 14:29 UTC
Access to nvchad.com  in chrome returns an ERR_SSL_PROTOCOL_ERROR.  Also, `curl https://nvchad.com` returns

```
curl: (35) error:0A000438:SSL routines::tlsv1 alert internal error
```

**Comment by siduck** [comment] 2023-04-20 14:45
duplicate of https://github.com/NvChad/nvchad.github.io/issues/147 

does nvchad.netlify.app work?

**Closed as completed by siduck** 2023-04-20 14:45 UTC

**Comment by siduck** [comment] 2023-04-24 15:51
@oec does it work now?

**Comment by oec** [comment] 2023-04-28 12:31
yep, I can access https://nvchad.com again.
