### ISSUE TITLE
Theme not work at first time with neovim@0.10.0

### ISSUE THREAD

**Issue by JiuRanYa** [siduck76/NvChad#2855] opened 2024-05-24 08:04 UTC
**Describe the bug**

Theme not work at first time with neovim@0.10.0

![image](https://github.com/NvChad/NvChad/assets/58846658/aa2e3aa3-eca8-4710-bae7-c64e02f1ec36)

But it works if I change the theme

![image](https://github.com/NvChad/NvChad/assets/58846658/8ec4f884-20e4-40fd-b1bf-faa56c6d4f07)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim

**Additional context**

**Comment by rklak** [comment] 2024-05-24 09:15
I agree, I was looking if someone has this problem too, so I am glad that this is not only at my Ubuntu. Waiting for fix.

**Comment by JiuRanYa** [comment] 2024-05-24 09:33
It's just happen with `neovim@0.10.0`. Maybe need to compact with that.

**Comment by siduck** [comment] 2024-05-24 10:35
impossible, please show your init.lua file

**Comment by siduck** [comment] 2024-05-24 10:35
i'm assuming you all changed the nvim-treesitter config function which also loaded our syntax files

**Comment by rklak** [comment] 2024-05-24 10:46
OK, so here's my story.

My .config for nvchad: https://github.com/rklak/dotfiles/tree/main/private_dot_config/nvim

neovim v.0.9.5 was installed via llinuxbrew on Ubuntu 24.00

`:checkhealth` (there are indeed some warnings, maybe thats the case?)
![image](https://github.com/NvChad/NvChad/assets/2330316/a834c22d-113d-45cc-a972-572dbdde7f0c)

**Comment by siduck** [comment] 2024-05-24 10:48
i cant reproduce it   :/

**Comment by siduck** [comment] 2024-05-24 10:48
y'all please show a video of vanilla nvchad installation + TSINstall whatever lang

**Comment by rklak** [comment] 2024-05-24 10:52
Do you know where nvchad stores the information about selected theme? Maybe there is a privilage problem? just a guess durring installation… sudo/no sudo

**Comment by rklak** [comment] 2024-05-24 11:22
Ok, so I won't  attach the video, because on clean install:
`git clone https://github.com/NvChad/starter . && nvim -c ":TSInstall rust"`

When I change theme and rerun nvim, all was working, so my config breaks the theme meomization

so first I will try to get rid off warnings from `:checkhealth` - its not  a problem of NvChad than…

**Comment by siduck** [comment] 2024-05-24 11:37
@rklak      i tried your config and its working fine

**Comment by rklak** [comment] 2024-05-24 11:37
Ok, so something was cached… ? When I have replace the nvim diredctory with my backuped config(before clean install check) everything was working… what have I done?

`cp -r ~/.config/nvim ~/.config/nvim.backup` 
`sudo rm -rf ~/.config/nvim/` (until all files are cleaned…)
`git clone https://github.com/NvChad/starter . && nvim -c ":TSInstall rust"`
`sudo rm -rf ~/.config/nvim/` (unitl all files are cleaned...)
`cp -r ~/.config/nvim.backup/ ~/.config/nvim/`
`nvim` and change the theme
close nvim
`nvim` 

it works, theme stays the same

**Comment by siduck** [comment] 2024-05-24 11:38
wait, i just did lazy sync and whole colorscheme changed lol! lemme test properly

**Comment by siduck** [comment] 2024-05-24 11:39
@rklak can you show a video of your config not working? so i can reproduce here

**Comment by siduck** [comment] 2024-05-24 11:40
![image](https://github.com/NvChad/NvChad/assets/59060246/976f545f-9380-4233-b29a-173686893380)
looks fine here

**Comment by siduck** [comment] 2024-05-24 11:45
since i and u all cant reproduce on vanilla nvchad, then i'm closing it.Bring forth a video with reproduction steps and config then i'll re-open this

**Closed as completed by siduck** 2024-05-24 11:45 UTC

**Comment by JiuRanYa** [comment] 2024-05-27 02:43
Hi, everyone. I just fond that if i using this tree-sitter config, theme will not work

Hope to help you.@rklak 

```lua
	{
		"nvim-treesitter/nvim-treesitter",
		event = "VeryLazy",
		config = function()
			require("nvim-treesitter.configs").setup({
				ensure_installed = { "javascript", "html", "json", "vue", "vim", "typescript", "scss" },
				-- If I set enable is true, problem happened.
				highlight = {
					enable = false,
					additional_vim_regex_highlighting = false,
				},
				autotag = {
					enable = true,
				},
				-- 启用代码缩进模块 (=)
				indent = {
					enable = true,
				},
				-- p00f/nvim-ts-rainbow
				rainbow = {
					enable = true,
					-- disable = { "jsx", "cpp" }, list of languages you want to disable the plugin for
					extended_mode = true, -- Also highlight non-bracket delimiters like html tags, boolean or table: lang -> boolean
					max_file_lines = nil, -- Do not enable for files with more than n lines, int
					colors = {
						"#95ca60",
						"#ee6985",
						"#D6A760",
						"#7794f4",
						"#b38bf5",
						"#7cc7fe",
					}, -- table of hex strings
					-- termcolors = { } -- table of colour name strings
				},
			})
		end,
	},


```

**Comment by JiuRanYa** [comment] 2024-05-27 02:47
Hi, everyone. I just fond that if i using this tree-sitter config, theme will not work

Hope to help you.@rklak
```lua
	{
		"nvim-treesitter/nvim-treesitter",
		event = "VeryLazy",
		config = function()
			require("nvim-treesitter.configs").setup({
				ensure_installed = { "javascript", "html", "json", "vue", "vim", "typescript", "scss" },
				-- If I set enable is true, problem happened.
				highlight = {
					enable = false,
					additional_vim_regex_highlighting = false,
				},
				autotag = {
					enable = true,
				},
				-- 启用代码缩进模块 (=)
				indent = {
					enable = true,
				},
				-- p00f/nvim-ts-rainbow
				rainbow = {
					enable = true,
					-- disable = { "jsx", "cpp" }, list of languages you want to disable the plugin for
					extended_mode = true, -- Also highlight non-bracket delimiters like html tags, boolean or table: lang -> boolean
					max_file_lines = nil, -- Do not enable for files with more than n lines, int
					colors = {
						"#95ca60",
						"#ee6985",
						"#D6A760",
						"#7794f4",
						"#b38bf5",
						"#7cc7fe",
					}, -- table of hex strings
					-- termcolors = { } -- table of colour name strings
				},
			})
		end,
	},
```

**Comment by JiuRanYa** [comment] 2024-05-27 02:57
@siduck I dont' make sure this is a bug with treesitter.config. But using the nvchad default config with treesitter config below, theme will lose work.

**Comment by siduck** [comment] 2024-05-27 03:19
@JiuRanYa  cuz our default config loads the syntax highlight groups

![image](https://github.com/NvChad/NvChad/assets/59060246/468bbd1f-5b8a-4880-b8cb-fc3645e0b5c8)

Also your code is bad, you dont have to do all of that at all

```lua
	{
	    "nvim-treesitter/nvim-treesitter",
 	     opts  = {
			ensure_installed = { "javascript", "html", "json"},
				 
			highlight = {
				enable = true,
			},
				
	         --   more options 
        	}
	},
```

for overriding any plugin in nvchad, you  can pass your options in just the opts table, and that will merge with our default opts

**Comment by JiuRanYa** [comment] 2024-05-27 03:40
Thanks! With highlight enable `false` also weird. I just delete this.
